# Name: luogu-problem-difficulty
# Description: 统计（通过）的洛谷题目的难度。

# 用户id UserID
# >> 默认是我（memset0）的用户ID
#    多个账号请用逗号分隔
UserID: 53495, 53062

# 是否已经统计过 hasStatisticsed
# >> 如果已经统计过（已经有生成 log/ans.txt 就可以设置为 true）
#    除非你想要重新统计一遍
hasStatisticsed: false

# 是否开启 Debug 模式 debug
debug: false