# Name: luogu-problem-difficulty
# Description: 统计（通过）的洛谷题目的难度。

# 用户id UserID
# >> 默认是我（memset0）的用户ID
UserID: 53495

# 限制爬取的数据量 limitCount
# >> 如果不需要限制的话设置为-1即可，用于调试
limitCount: -1

# 是否已经统计过 hasStatisticsed
# >> 如果已经统计过（已经有生成 log/ans.txt 就可以设置为 true）
#    除非你想要重新统计一遍
hasStatisticsed: false